- name: Debug PATH e ferramentas
        run: |
          echo "PATH atual: $PATH"
          which ee-gcc || echo "ee-gcc não encontrado!"
          which dvp-as || echo "dvp-as não encontrado!"
          ls \~/ps2dev/bin || echo "bin não encontrado!"
          ls \~/ps2dev/ps2sdk || echo "ps2sdk não encontrado!"

      - name: Debug PS2SDK vars
        run: |
          echo "PS2DEV=$PS2DEV"
          echo "PS2SDK=$PS2SDK"
          ls $PS2SDK/samples || echo "samples não encontrado!"
